{% set version = "2.0.1" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: 1ffac0228aa83f04a1b1cf2788a3af5953e82587ae3a77c41900e99f2557132d
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - patches/0001-Deactivate-aggressive-failures-on-warnings.patch
    - patches/0002-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch
    - patches/0003-CMake-Add-more-hints-for-libraries-on-Windows.patch
    - patches/0004-don-t-force-lib-destination.patch
    - patches/0005-Check-for-protobuf-config-based-module.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("orc", max_pin="x.x.x") }}      
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
    - patch  # [not win]
    - ninja-base  # [unix]
    # `protoc` is also used for building
    - libprotobuf 4.25.3
    - cmake
  host:
    - zlib {{ zlib }}
    - snappy 1.1.10
    - libprotobuf 4.25.3
    - libabseil 20240116.2 # [win] linked with orc.dll through libprotobuf dep.
    - lz4-c 1.9.4
    - zstd {{ zstd }}
  run:
    # through run exports
    - zlib
    - snappy
    - libprotobuf
    - libabseil  # [win]
    - lz4-c
    - zstd
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]
    # orc >=2.0.1 will prefer $CONDA_PREFIX/share/zoneinfo for tzdb
    - tzdata

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/liborc${SHLIB_EXT}     # [unix]
    - if not exist %LIBRARY_BIN%\orc.dll exit 1  # [win]
    # import library for the DLL
    - if not exist %LIBRARY_LIB%\orc.lib exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/liborc.a             # [not win]

    # headers
    - test -f $PREFIX/include/orc/Common.hh            # [unix]
    - if not exist %LIBRARY_INC%\orc\Common.hh exit 1  # [win]

about:
  home: https://orc.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC
  dev_url: https://github.com/apache/orc
  doc_url: https://github.com/apache/orc#readme
  description: The smallest, fastest columnar storage for Hadoop workloads.

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - nehaljwani
