{% set version = "1.6.0" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: 2d864000c60025f54631e0dff1a943380e7578277688a4e333ad7d9ac7d29747
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch

build:
  number: 0
  skip: True    # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
  run:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/lib/liborc.a  # [unix]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C++ libraries for Apache ORC'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
