{% set version = "1.7.4" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: 0a70c5e877b1ff268e768c94392574a084092f8aa7f97796c13de276103d8272
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch
    - 0003-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch
    # The build system looks for lz4.lib and protobuf.lib, but our libs are
    # called liblz4.lib and libprotobuf.lib.
    - 0004-find-libs-on-windows.patch  # [win]
    - 0005-fix_cmake_zlib_linking.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("orc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-base  # [win]
    - m2-patch  # [win]
    - patch  # [not win]
    - ninja  # [unix]
    # `protoc` is also used for building
    - libprotobuf
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/liborc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/orc/Common.hh   # [unix]
    - if not exist %PREFIX%\\Library\\bin\\orc.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\orc.lib exit 1  # [win]

about:
  home: https://orc.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC
  dev_url: https://github.com/apache/orc
  doc_url: https://github.com/apache/orc#readme
  description: The smallest, fastest columnar storage for Hadoop workloads.

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - nehaljwani
