{% set version="1.5.1" %}

package:
  name: orc
  version: {{ version }}

source:
  fn: orc-{{ version }}.tar.gz
  url: https://github.com/apache/orc/archive/rel/release-{{ version }}.tar.gz
  sha256: 41b4f06ab425c875987b4b6fc9e347b2b434dcc768d0537708a310bb5e6277ce

build:
  number: 0
  skip: True    # [linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make       # [unix]
  host:
    # putting cmake in host allows it to find the cmake modules better
    - cmake
    - zlib
    - snappy
    - libprotobuf  {{ protobuf }}
    - lz4-c
  run:
    - protobuf
