{% set version="1.5.2" %}

package:
  name: orc
  version: {{ version }}

source:
  fn: orc-{{ version }}.tar.gz
  url: https://github.com/apache/orc/archive/rel/release-{{ version }}.tar.gz
  sha256: 8b0a9e50281f5ea5647c0ac384b5de9dd0b98726a501eae9f568df6833a716c0

build:
  number: 0
  skip: True    # [linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make       # [unix]
  host:
    # putting cmake in host allows it to find the cmake modules better
    - cmake
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
  run:
    - protobuf
